# Generated by Django 5.2.9 on 2025-12-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="封面"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="workflows.workflowcategory",
                        verbose_name="父级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流分类",
                "verbose_name_plural": "工作流分类",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "start_node",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="开始节点"
                    ),
                ),
                (
                    "end_node",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="结束节点"
                    ),
                ),
                (
                    "node_details",
                    models.TextField(blank=True, null=True, verbose_name="节点详情"),
                ),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="封面"
                    ),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="演示视频"
                    ),
                ),
                (
                    "attachment",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="附件"
                    ),
                ),
                (
                    "reference",
                    models.TextField(blank=True, null=True, verbose_name="参考资料"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="标签"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "草稿"), ("PUBLISHED", "发布")],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "access_level",
                    models.IntegerField(default=0, verbose_name="访问权限"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="workflows.workflowcategory",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流",
                "verbose_name_plural": "工作流",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
