# Generated by Django 5.1.2 on 2025-12-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="", max_length=50),
        ),
    ]
