# Generated by Django 5.1.2 on 2025-12-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1, verbose_name="用户等级"),
        ),
    ]
