# Generated by Django 5.1.2 on 2025-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
