# Generated by Django 5.1.2 on 2025-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_expire_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="会员过期时间"
            ),
        ),
    ]
