# Generated by Django 5.1.2 on 2025-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_membership_expire_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_reference_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="当前会员参考总价",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_reference_days",
            field=models.IntegerField(default=0, verbose_name="当前会员参考总天数"),
        ),
    ]
