# Generated by Django 5.1.2 on 2025-12-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="会员名称")),
                ("level", models.IntegerField(default=1, verbose_name="会员等级权重")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(default=30, verbose_name="有效期(天)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="权限描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "会员套餐",
                "verbose_name_plural": "会员套餐",
                "db_table": "membership_plans",
                "ordering": ["level", "price"],
            },
        ),
        migrations.CreateModel(
            name="MemberOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=32, unique=True, verbose_name="订单号"),
                ),
                (
                    "plan_name",
                    models.CharField(max_length=50, verbose_name="套餐名称快照"),
                ),
                ("plan_days", models.IntegerField(verbose_name="套餐天数快照")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待支付"),
                            ("PAID", "已支付"),
                            ("CANCELLED", "已取消"),
                            ("REFUNDED", "已退款"),
                            ("EXPIRED", "已过期"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("WECHAT", "微信支付"), ("ALIPAY", "支付宝")],
                        max_length=20,
                        null=True,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="membership.membershipplan",
                        verbose_name="会员套餐",
                    ),
                ),
            ],
            options={
                "verbose_name": "会员订单",
                "verbose_name_plural": "会员订单",
                "db_table": "member_orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
