# Generated by Django 5.1.2 on 2025-12-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplan",
            name="duration_unit",
            field=models.CharField(
                choices=[
                    ("DAY", "天"),
                    ("WEEK", "周"),
                    ("MONTH", "月"),
                    ("YEAR", "年"),
                ],
                default="MONTH",
                max_length=10,
                verbose_name="有效期单位",
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="duration_value",
            field=models.IntegerField(default=1, verbose_name="有效期数值"),
        ),
    ]
