# Generated by Django 5.1.2 on 2025-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_membershipplan_duration_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplan",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="原价",
            ),
        ),
    ]
