# Generated by Django 5.1.2 on 2025-12-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_membershipplan_original_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberorder",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="抵扣金额"
            ),
        ),
        migrations.AddField(
            model_name="memberorder",
            name="order_type",
            field=models.CharField(
                choices=[("NEW", "新购"), ("RENEWAL", "续费"), ("UPGRADE", "升级")],
                default="NEW",
                max_length=10,
                verbose_name="订单类型",
            ),
        ),
        migrations.AlterField(
            model_name="memberorder",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="实付金额"
            ),
        ),
    ]
