# Generated by Django 5.2.9 on 2025-12-05 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership",
            "0004_memberorder_discount_amount_memberorder_order_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("PAYMENT", "支付"), ("REFUND", "退款")],
                        max_length=10,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易金额"
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="第三方交易号",
                    ),
                ),
                ("platform", models.CharField(max_length=20, verbose_name="支付平台")),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "成功"), ("FAILED", "失败")],
                        default="SUCCESS",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(blank=True, null=True, verbose_name="原始响应"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="membership.memberorder",
                        verbose_name="关联订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付流水",
                "verbose_name_plural": "支付流水",
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
