# Generated by Django 5.1.2 on 2025-12-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "cover",
                    models.CharField(
                        blank=True,
                        help_text="COS URL",
                        max_length=255,
                        verbose_name="封面图URL",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序值")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="courses.coursecategory",
                        verbose_name="父级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程分类",
                "verbose_name_plural": "课程分类",
                "db_table": "course_categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="课程名称")),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="封面图URL"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="课程描述")),
                (
                    "instructor",
                    models.CharField(
                        help_text="讲师姓名", max_length=50, verbose_name="讲师姓名"
                    ),
                ),
                (
                    "access_level",
                    models.IntegerField(
                        default=0,
                        help_text="0:免费, >0:所需会员等级",
                        verbose_name="访问权限",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UPDATING", "更新中"), ("FINISHED", "已完结")],
                        default="UPDATING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序值")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.coursecategory",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "courses",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="章节名称")),
                ("description", models.TextField(blank=True, verbose_name="章节描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序值")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程章节",
                "verbose_name_plural": "课程章节",
                "db_table": "course_chapters",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="课时标题")),
                ("description", models.TextField(blank=True, verbose_name="课时描述")),
                (
                    "video_cover",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="视频封面"
                    ),
                ),
                (
                    "video_file_id",
                    models.CharField(
                        help_text="腾讯云VOD FileId",
                        max_length=100,
                        verbose_name="视频FileId",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序值")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.coursechapter",
                        verbose_name="所属章节",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课时",
                "verbose_name_plural": "课时",
                "db_table": "course_lessons",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
