# Generated by Django 5.2.9 on 2025-12-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courselesson",
            name="video_cover",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="cover",
            field=models.CharField(
                blank=True,
                help_text="VOD cover url",
                max_length=255,
                verbose_name="视频封面",
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="video_url",
            field=models.CharField(
                blank=True,
                help_text="VOD video url",
                max_length=500,
                verbose_name="视频播放地址",
            ),
        ),
    ]
