# Generated by Django 5.2.9 on 2025-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_courselesson_video_cover_courselesson_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselesson",
            name="duration",
            field=models.CharField(
                blank=True, help_text="e.g. 08:50", max_length=20, verbose_name="时长"
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="resolution",
            field=models.CharField(
                blank=True,
                help_text="e.g. 1920x1080",
                max_length=20,
                verbose_name="分辨率",
            ),
        ),
    ]
